language: "de"

# pipeline: spacy_sklearn

pipeline: 
  - name: "nlp_spacy"
  - name: "tokenizer_spacy"
  - name: "intent_entity_featurizer_regex"
  - name: "intent_featurizer_spacy"
  - name: "ner_crf"
  - name: "ner_duckling_http"
    # url of the running duckling server
    url: "http://duckling:8000"
    # dimensions to extract
    dimensions: ["time"]
    # allows you to configure the locale, by default the language is
    # used
    locale: "de_DE"
    # if not set the default timezone of Duckling is going to be used
    # needed to calculate dates from relative expressions like "tomorrow"
    timezone: "Europe/Berlin"
  - name: "intent_classifier_sklearn"