version: '3.7'

services:
  rasa:
    image: rasa/rasa_nlu:latest-full
    networks: ['rasa-network']
    ports:
    - "5000:5000"
    volumes:
    - "./models:/app/models"
    - "./config:/app/config"
    - "./data:/app/data"
    command: ["start", "--path", "/app/models",]
    
  duckling:
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8000:8000"
    expose:
    - "8000" 

networks: {rasa-network: {}} 